name: Validate Packer

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: AWS config
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Packer init
      run: packer init ./scripts/setup.pkr.hcl
    
    - name: Zip web app
      run: |
        zip -r webapp.zip server/
    
    - name: Packer format
      working-directory: ./scripts/
      run: packer fmt -check setup.pkr.hcl
    
    - name: Packer validate
      working-directory: ./scripts/
      run: packer validate setup.pkr.hcl
   