name: Validate Packer 

on:
	pull_request:
		types: [closed]
		branches: [ "main" ]

jobs:
	packer:
		runs-on: ubuntu-latest

		steps:
			- name: Checkout repo
			  uses: actions/checkout@v2
			
			- name: AWS config
				uses: aws-actions/configure-aws-credentials@v1
				with:
					aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
					aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
					aws-region: us-east-1
      
			- name: Packer init
      	run: packer init ./scripts/setup.pkr.hcl
<<<<<<< HEAD

=======
				
>>>>>>> 2793f6c625c1d12df1ac5c6a1b3c31f6807b6108
      - name: Packer build
				run: packer build ./scripts/setup.pkr.hcl
