name: Validate Packer

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: AWS config
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Packer init
      run: packer init scripts/aws.pkr.hcl
    
    - name: Packer format
      run: packer fmt -check -on-error=abort scripts/aws.pkr.hcl
    
    - name: Packer validate
      run: packer validate -on-error=abort scripts/aws.pkr.hcl
   